export const CartActionTypes = {
  HIDE_CART: 'HIDE_CART',
  SHOW_CART: 'SHOW_CART',
  TOGGLE_HIDE_CART: 'TOGGLE_HIDE_CART',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  SUBSTRACT_ITEM: 'SUBSTRACT_ITEM',
};